apiVersion: v2
description: Prometheus Blackbox Exporter
name: prometheus-blackbox-exporter
version: 0.5.0-dev
appVersion: 0.23.0
annotations:
  io.giantswarm.application.team: "phoenix"
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
sources:
  - https://github.com/prometheus/blackbox_exporter
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
keywords:
  - prometheus
  - blackbox
  - monitoring
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
maintainers:
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: gianrubio
    email: gianrubio@gmail.com
  - name: rsotnychenko
    email: me@sota.sh
  - name: monotek
    email: monotek23@gmail.com
type: application
